sudo: required

services:
  - docker

addons:
  ssh_known_hosts:
    secure: "ssIVzLrZRPwrNZkzZR4zaa+QwLccx2WvCpuoj6+Nwb83i59HRjV0LbSRdXhqEqOTNrQSTWruRt9OPgaV3pTrWUpVh+xlDQtFdI2BaS7+OI0uAVH3BEkcY/cV/J6bxihkw4PWX3JzpeeD0dDAX4tVxSRptFX+/mYfaTBmPiDeDOq+3R45bDE2W0BkBcqTr3NZqEhkz2njtuf5nk7RbjS8+xq79+P1N5/od6jxznpL9rqHBFSABudllYYRIAV5AsiCjOc7PJ4IXNYJMMvTyHgXG9wDnSSnd6J3jsnt96dq9hzGqECVNJmToYWdP6WthYBGloZP96V7Lytd7fOROjuPE1NDTxz9Jf1/pm+3xaecsF70XvDkAdK38m/QlXPlFphBaAkp8ijwbFkK1bUlMdXpeOPcg7CowD9o/jn8web3ZPC9swcKiUv/5lSGAl6+ihN5MtuQZ7uExBIMXHWl2zokisRQ5sLpDg/pnbISsX5NvNa830OXPmoRf4YlDsUxpBNFNMBf2LEiWsWHA5foAhQzDnpMZm3A6NBxunz1i3dECZ++jPwJn+hNvISpRx+37TmYxeEES1jUJ38PXhtE9xFs7vxeb19MkR+nqC065B8eX754O7/NTs34CKJQfetPTUrtoTFVWmMiC/7mGsK30682smbD2rRXWiM7i+ceI9jJjho="

before_install:
- openssl aes-256-cbc -K $encrypted_3dce006c1517_key -iv $encrypted_3dce006c1517_iv
  -in id_rsa.enc -out /tmp/id_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/id_rsa
- ssh-add /tmp/id_rsa

matrix:
  include:
    - language: python
      python: 3.6
      script:
        - echo script_step
      env:
        - APP_ID=python_app

    - language: node_js
      node_js:
        - "node"
      script:
        - echo script_step
      env:
        - APP_ID=node_app

script:
- echo "Script step"

after_success:
- echo "Success step"

deploy:
- provider: script
  script: bash ssh_deploy.sh $DOCKER_PYTHON_APP $PYTHON_APP_PORT_EXTERNAL $PYTHON_APP_PORT_INTERNAL
  on:
    condition: $APP_ID = python_app
- provider: script
  script: ssh $DEPLOY_HOST_USERNAME@$DEPLOY_HOST -p $DEPLOY_HOST_PORT 'echo test > ssh_node_test.txt'
  on:
    condition: $APP_ID = node_app

env:
  global:
  - DOCKER_PYTHON_APP=python-app
  - PYTHON_APP_PORT_EXTERNAL=8080
  - PYTHON_APP_PORT_INTERNAL=5000

  - secure: h9uR3n3q+PEk1Bbida9ZI/9CHlIx9mczF4ZgF+SH2KmdklPyS8xEdrdj2Vi2C3X3fhmlo0CXvzPoeHk7XC+Tv/oG1XKinNiGY/GWfAfL8qWVzq20sl4rvliTfczXBP4qHJb+llzp1KeWy5ZJ5t7GoCBBA9XS6EinIzTm4etXOqf8maculA4aXhTcgmc1HzcH5hzQcioSiRILdZeTkgANMOFhubc96Rg2tI3Xks2bwdwWddMUiN2Q10g6Nxf7mGfQ/BH6LzViHn2HB+lE1oPQRIItfpEZVmaW7A/X3YvWnaHBvs/pbn75JiqO2xSgE4JS6A6+N+CP/KjMziUZ2YLzH7LPfpeEJX53t+sgIRpOWShJqjQBYtE/6EVkjV5WdXNkDKK6m62SCjIJdBcNIWV8yrzpY4TjogebV+Qpfpq6v7+FO9VNLlw4mOtuHEkcyWPhBgO90LIrwtTrvZ1yJTNKeykRQ9dvU7RnFVhqMA1e+9bqAiUyhm84iFy35o3OEH6hGJdE2E/A95cpUVg+BIwk/7a95cQNLzsi9XY/U+GtLn7RcyDVMLaOHNXz0JNuLSd2hIG4hVGZ84P7h9G2ufE5pbjm5brZO80JF5E7iqiLev1ptfO7fI7OFy91a3N3FxZ2rKlBxFystplUSfxmrsvffFl5P68dUSsnVvO9Lq9Y5ZY=
  - secure: mjJlJhPdE36HCEqtgi+LtQ4SGKrb3QV2O7XsG8DdtgemhGI1Thq0BgAppfdSLNN2W5hLFnbsjgZZ4fDB2hA+SPKMJVS0qaFWWmUim2T+3dNFZE3Pv4oHJzpyi9rx70sz+yB8nVI8ee7GG9SS1wSlfwCn5lOT3ACMrgsZvJ2a3enLPzOUf5AYnwGOo9JaERpbrlbiTFI+MCN59eBzMM62stJNMkjSNtlixv8rTslc4mzWbJg/aFu5X3JcR8yp7CqHF+8ZcR6Q4z01ec8e7GGp8Mo540xSAr+gWaOFK44FZqIclJ6XqhowjOr/VYdmgtdNVWilVEGZKQr/wzD1crsLMRyXkRt3Hzns2cJUe6q/gamPeA/IhNBYEmfyhWjdf26KnP1YYX9fns8gshdEsCyGvs+jel7wjrw0uTgN3yW+iCNvogGvIqo+HX45AIjHAREjppe98fayOhg0bVQAvluchM9rSKkqoJUsfuJHHgvBWcOafsxxFJ0VHeBf0cgRRdfgyGP3vhDUhtbSwaSq9H08/HIhKuhs8av+ypBjukxH7Hzca5J1PxyAky+OXrMKpX9v8SwDwWTPi7Q7MmW62Dv1Ztf85oYq9eup8bUixefVoTn5UqZa7gADoxJomPTsDtR9EEeWYRV6+H0qDQGxhGzH0VNTfviSmPOtyG8/H2c5VZ0=
  - secure: cDN5fwfg/sxnhwl6xf1v763anXFXAWgpIoHW0nIcxY7iOoi7OqFq6HjwOQmIKJ/2mERYEK3PnTg+SnBgMxa5X+wudlSC0TlsZj/cAiq2FWDnOH9IeQmv+OXtEcwV5uSRKUHelvPR+DyjtUVVyv90kX4MOwLhs39qbphSJliazk7UsqP2mei44STF9jE+En6zYwwvGI29DOv2e82PX5aK5aTTGSB8701W6v2bP+gP+4Js/HuxrASBHn+1bf1EFrzz8IbLiNtfgjTZlTtnNyCP5VH8SzGkc/GCYvjPWT4vI3NB+1tF8OuRRMPiynrc0FpdnaKvo7akZCa/YBmr8ktYs+nsgyZcsuUms6lFY8VQP9TuJbDYt4FQjindi3ghW7Ct1dOSgOcCiwJfr8sPOmy5dLJvkVF1+Yww27lwSfyTXdfVDBAIllZudkgTSt9AIVnwAtj8u/nx/tQFXyDFOZaEboRLwv+aoNTriQUWTVwI+0P4ARZ6MTcwDuS+D1jG7tfbXodH6RwV3MAmGkgTR9TUGuw+Tbi8Iq6uQ9jAdr70EvxXMLoLPxx8NcHP8rVpQmLFGW5zlQunoSnZWxKTgoBZ+qV5gg3SNIJ3Ce6VmXglI4b5rpVLzP5K2GvFdmiDMmshbGm/TiiHaTug+u5BdkDqmVqHisCclhtpGLuf3uWT//o=
