addons:
  ssh_known_hosts:
    secure: "ssIVzLrZRPwrNZkzZR4zaa+QwLccx2WvCpuoj6+Nwb83i59HRjV0LbSRdXhqEqOTNrQSTWruRt9OPgaV3pTrWUpVh+xlDQtFdI2BaS7+OI0uAVH3BEkcY/cV/J6bxihkw4PWX3JzpeeD0dDAX4tVxSRptFX+/mYfaTBmPiDeDOq+3R45bDE2W0BkBcqTr3NZqEhkz2njtuf5nk7RbjS8+xq79+P1N5/od6jxznpL9rqHBFSABudllYYRIAV5AsiCjOc7PJ4IXNYJMMvTyHgXG9wDnSSnd6J3jsnt96dq9hzGqECVNJmToYWdP6WthYBGloZP96V7Lytd7fOROjuPE1NDTxz9Jf1/pm+3xaecsF70XvDkAdK38m/QlXPlFphBaAkp8ijwbFkK1bUlMdXpeOPcg7CowD9o/jn8web3ZPC9swcKiUv/5lSGAl6+ihN5MtuQZ7uExBIMXHWl2zokisRQ5sLpDg/pnbISsX5NvNa830OXPmoRf4YlDsUxpBNFNMBf2LEiWsWHA5foAhQzDnpMZm3A6NBxunz1i3dECZ++jPwJn+hNvISpRx+37TmYxeEES1jUJ38PXhtE9xFs7vxeb19MkR+nqC065B8eX754O7/NTs34CKJQfetPTUrtoTFVWmMiC/7mGsK30682smbD2rRXWiM7i+ceI9jJjho="

before_install:
- openssl aes-256-cbc -K $encrypted_3dce006c1517_key -iv $encrypted_3dce006c1517_iv
  -in id_rsa.enc -out /tmp/id_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/id_rsa
- ssh-add /tmp/id_rsa

script:
- echo "Script step"

after_success:
- echo "Success step"

deploy:
- provider: script
  script: ssh $DEPLOY_HOST_USERNAME@$DEPLOY_HOST -p $DEPLOY_HOST_PORT 'echo test > ssh_test.txt'

env:
  global:
  - secure: h9uR3n3q+PEk1Bbida9ZI/9CHlIx9mczF4ZgF+SH2KmdklPyS8xEdrdj2Vi2C3X3fhmlo0CXvzPoeHk7XC+Tv/oG1XKinNiGY/GWfAfL8qWVzq20sl4rvliTfczXBP4qHJb+llzp1KeWy5ZJ5t7GoCBBA9XS6EinIzTm4etXOqf8maculA4aXhTcgmc1HzcH5hzQcioSiRILdZeTkgANMOFhubc96Rg2tI3Xks2bwdwWddMUiN2Q10g6Nxf7mGfQ/BH6LzViHn2HB+lE1oPQRIItfpEZVmaW7A/X3YvWnaHBvs/pbn75JiqO2xSgE4JS6A6+N+CP/KjMziUZ2YLzH7LPfpeEJX53t+sgIRpOWShJqjQBYtE/6EVkjV5WdXNkDKK6m62SCjIJdBcNIWV8yrzpY4TjogebV+Qpfpq6v7+FO9VNLlw4mOtuHEkcyWPhBgO90LIrwtTrvZ1yJTNKeykRQ9dvU7RnFVhqMA1e+9bqAiUyhm84iFy35o3OEH6hGJdE2E/A95cpUVg+BIwk/7a95cQNLzsi9XY/U+GtLn7RcyDVMLaOHNXz0JNuLSd2hIG4hVGZ84P7h9G2ufE5pbjm5brZO80JF5E7iqiLev1ptfO7fI7OFy91a3N3FxZ2rKlBxFystplUSfxmrsvffFl5P68dUSsnVvO9Lq9Y5ZY=
  - secure: mjJlJhPdE36HCEqtgi+LtQ4SGKrb3QV2O7XsG8DdtgemhGI1Thq0BgAppfdSLNN2W5hLFnbsjgZZ4fDB2hA+SPKMJVS0qaFWWmUim2T+3dNFZE3Pv4oHJzpyi9rx70sz+yB8nVI8ee7GG9SS1wSlfwCn5lOT3ACMrgsZvJ2a3enLPzOUf5AYnwGOo9JaERpbrlbiTFI+MCN59eBzMM62stJNMkjSNtlixv8rTslc4mzWbJg/aFu5X3JcR8yp7CqHF+8ZcR6Q4z01ec8e7GGp8Mo540xSAr+gWaOFK44FZqIclJ6XqhowjOr/VYdmgtdNVWilVEGZKQr/wzD1crsLMRyXkRt3Hzns2cJUe6q/gamPeA/IhNBYEmfyhWjdf26KnP1YYX9fns8gshdEsCyGvs+jel7wjrw0uTgN3yW+iCNvogGvIqo+HX45AIjHAREjppe98fayOhg0bVQAvluchM9rSKkqoJUsfuJHHgvBWcOafsxxFJ0VHeBf0cgRRdfgyGP3vhDUhtbSwaSq9H08/HIhKuhs8av+ypBjukxH7Hzca5J1PxyAky+OXrMKpX9v8SwDwWTPi7Q7MmW62Dv1Ztf85oYq9eup8bUixefVoTn5UqZa7gADoxJomPTsDtR9EEeWYRV6+H0qDQGxhGzH0VNTfviSmPOtyG8/H2c5VZ0=
  - secure: ZZyOWMvFBJsaqOf9CBG99Sw56nAqAhkEvdcQUT69pHLLv6twb5OgTBFMAgx8renozHqoxA4XVoQr0Z/T0cWd8a/8EofMTmF1n5/z0bEnfifTKizau3/MdmipWsNnX7u/MLpqggRqtk4QzCYuubPhgwqDLcfzZKgv9jaXAeJkLPcHfTVPLRm5mnL1uAtU7TeCZd+l7mk+daCZ9d23tUXofIBsrRYmdXxggFDnFR0YXYyFoGUd+yHtkSjJBcsw+WupSq+4W38po7Lzst98YOi8WEmMh9PMxRnpdDOCaAX0ELe6eNH6LDAtVxjuMrqe56F67Q29EbyEHayducmD4Gl/kpVvP5owN/pdrOXmYN2aa1DZzJp0wdL1CAjPBTl8NGJDr0xyQM4ZtAjY/qkjJwWhgvHwly3jVE+zORSb6WHba+Z1/dQx9lnKIJg56HHIT43I53x2gMSBref/scjRQvECqXKLIXb3rilmi0XagROEEbApjkHZMRjSqaknMVtm3DK798mz4s+/iNLlMZsZti2OBBLV71T2/7ds0TUYOBoFP+6zALtTAkKdLl3tZc5csMGGts2JBSst04OgJgGuz4xi3qGzFjAnkPYUs2Cq4sJym7JDZlEtuIqH5il1oQ1XP9tLXGHKCv3NTjA0b4TRpn+vWVkGZmF26wEgNMicJPN/gQI=
